# This is a basic workflow to help you get started with Actions

name: NonAzureCalls

# Controls when the workflow will run
on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #- uses: actions/checkout@v3
  
        # Runs a single command using the runners shellgit 
        - name: Run a one-line script
          run: echo Hi - this is a line on text - its intended to be shown as part of a github action
  
        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            echo And this is some more text.
            echo This time on a multi line
            echo Our next step is to log into Azure using a credential
           
        # - name: Unique Name Generator Action
        #   uses: TGPSKI/name-generator-node-action@v2
        #   id: generator
        #   with:
        #     separator: '_'
        #     length: '4'
        #     style: 'upperCase'

        # # - name: test generator output
        # #   run: echo "latest,${{ steps.generator.outputs.name }}"
        
  

      
