# This is a basic workflow to help you get started with Actions

name: UsingVariables
#define environment variables
env:
    resoure_name: myname
    var1: WorkflowVariable1
    var2: WorkflowVariable2
###########################################

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #define jog variables
#   env:
#         varJob1:the value
  # This workflow contains a single job called "build"
  build:
    # env:
    #     job1:dfdfsdsdf
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # env:
        #     resoure_name: myname
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Print out to screen the environment variables
      - name: Run a one-line script
        env:
            martin: StepVariable1
        run: |
            echo Hello, world!
            # output the environment variables
            echo ${{ env.resoure_name}}
            echo ${{ env.var1}}
            echo ${{ env.var2}}
            echo ${{ env.martin}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
